name: pet_rock_flutter
description: Flutter frontend for Pet Rock with Supabase auth and multi-tenancy.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.1
  http: ^1.2.0
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
